


const CREATE_SERVICE = "CREATE_SERIVCE"
const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS"
const CREATE_SERIVCE_FAILURE = "CREATE_SERVICE_FAILURE"

const UPDATE_SERVICE = "UPDATE_SERVICE"
const UPDATE_SERVICE_FAILURE = "UPDATE_SERVICE_FAILURE"
const UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS"

const GET_LIST_SERVICE = "GET_LIST_SERVICE"
const GET_LIST_SERVICE_SUCCESS = "GET_LIST_SERVICE_SUCCESS"
const GET_LIST_SERVICE_FAILURE = "GET_LIST_SERVICE_FAILURE"

const DELETE_SERVICE = "DELETE_SERVICE"
const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS"
const DELETE_SERVICE_FAILURE = "DELETE_SERVICE_FAILURE"


interface ServiceItem {
    name: string,
    id: number | string,
    price: string,
}

interface ServiceState {
    loading: boolean,
    error: string,
    listService: ServiceItem[]
}


export {
    ServiceItem,
    ServiceState,

    GET_LIST_SERVICE,
    GET_LIST_SERVICE_FAILURE,
    GET_LIST_SERVICE_SUCCESS,

    UPDATE_SERVICE,
    UPDATE_SERVICE_SUCCESS,
    UPDATE_SERVICE_FAILURE,

    CREATE_SERVICE,
    CREATE_SERVICE_SUCCESS,
    CREATE_SERIVCE_FAILURE,

    DELETE_SERVICE,
    DELETE_SERVICE_FAILURE,
    DELETE_SERVICE_SUCCESS,
}