const CREATE_BRANCH = "CREATE_BRANCH"
const CREATE_BRANCH_SUCCESS = "CREATE_BRANCH_SUCCESS"
const CREATE_BRANCH_FAILURE = "CREATE_BRANCH_FAILURE"

const GET_BRANCH = "GET_BRANCH"
const GET_BRANCH_SUCCESS = "GET_BRANCH_SUCCESS"
const GET_BRANCH_FAILURE = "GET_BRANCH_FAILURE"

const UPDATE_BRANCH = "UPDATE_BRANCH"
const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS"
const UPDATE_BRANCH_FAILURE = "UPDATE_BRANCH_FAILURE"

const DELETE_BRANCH = "DELETE_BRANCH"
const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS"
const DELETE_BRANCH_FAILURE = "DELETE_BRANCH_FAILURE"

interface BranchItem {
    id: number;
    brandName: string;
    status: boolean
}
interface BranchState {
    loading: boolean,
    listBranch: BranchItem[],
    error: string,
}

export {
    BranchItem,
    BranchState,

    GET_BRANCH,
    GET_BRANCH_FAILURE,
    GET_BRANCH_SUCCESS,

    UPDATE_BRANCH,
    UPDATE_BRANCH_FAILURE,
    UPDATE_BRANCH_SUCCESS,

    CREATE_BRANCH,
    CREATE_BRANCH_FAILURE,
    CREATE_BRANCH_SUCCESS,

    DELETE_BRANCH,
    DELETE_BRANCH_FAILURE,
    DELETE_BRANCH_SUCCESS,
}